#!/bin/bash

BUILD_TIME=`date -u +%Y-%m-%d_%H:%M:%S`

docker build --build-arg GIT_COMMIT=$SOURCE_COMMIT --build-arg GIT_TREE_STATE="" --build-arg BUILD_TIME=$BUILD_TIME --build-arg VERSION=$DOCKER_TAG -t $IMAGE_NAME .