FROM registry.aliyuncs.com/zhangguanzhang/loong64:go1.21
# http://www.loongnix.cn/zh/toolchain/GNU/
RUN set -eux; \
    cd /; \
    wget http://ftp.loongnix.cn/toolchain/gcc/release/loongarch/gcc8/loongson-gnu-toolchain-8.3-x86_64-loongarch64-linux-gnu-rc1.1.tar.xz; \
    tar xfJp loongson-gnu-toolchain-*.tar.xz; \
    rm -f loongson-gnu-toolchain-*.tar.xz; \
    mv loongson-gnu-toolchain-*-x86_64-* loongson-gnu-toolchain

ENV PATH /loongson-gnu-toolchain/bin:$PATH
